apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: sb-k8s
build:
  tagPolicy:
    envTemplate:
      template: "buildpacks"
  artifacts:
    - image: nicolasduminil/k8s-sb
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base
        trustBuilder: true
        env:
          - "BP_JVM_VERSION=21"
manifests:
  rawYaml:
    - k8s/certificate.yaml
    - k8s/cluster-issuer.yaml
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/secret.yaml
    - k8s/service.yaml
portForward:
  - resourceType: service
    resourceName: sb-k8s
    port: 8443
    localPort: 8443
profiles:
  - name: reset
    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  - sh
                  - -c
                  - "kubectl delete secret sb-k8s-cert sb-k8s-ca sb-k8s-client-cert --ignore-not-found"
                os:
                  - linux
                  - darwin
